### ISSUE TITLE
The Apex Library has compatibility issues with the currently installed version of PyTorch (torch = = 1.10.1 + CU113) .

### ISSUE THREAD

**Issue by sunohm** [youmi-zym/CompletionFormer#24]
Hello, Can you help me to look at this error?
    The Apex Library has compatibility issues with the currently installed version of PyTorch (torch = = 1.10.1 + CU113) . An error occurred after running the environment that was installed according to the steps. 
     python main.py --dir_data nyudepthv2 --data_name NYU  --split_json data_json/nyu.json  --gpus 0 --max_depth 10.0 --num_sample 500 --save_image  --test_only --pretrain pretrained/NYUv2.pt --save hy-tmp/save
Traceback (most recent call last):
  File "CompletionFormer-main/CompletionFormer-main/src/main.py", line 42, in <module>
    import apex
  File "/usr/local/miniconda3/envs/completionformer/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/usr/local/miniconda3/envs/completionformer/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/usr/local/miniconda3/envs/completionformer/lib/python3.8/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/usr/local/miniconda3/envs/completionformer/lib/python3.8/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/usr/local/miniconda3/envs/completionformer/lib/python3.8/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/usr/local/miniconda3/envs/completionformer/lib/python3.8/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.8/dist-packages/torch/_six.py)

**Comment by youmi-zym** [comment]
Hi,

I'm sorry for not getting back to you sooner.  According to this note:

ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.8/dist-packages/torch/_six.py)

The issue may be due to the torch version.  Please search on Google to find a specific solution.

Best,
Youmin
